/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/scanner/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scanner Status
         * @description Get the current status of the scanner.
         */
        get: operations["get_scanner_status_api_scanner_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Scanner
         * @description Refresh the scanner database.
         */
        post: operations["refresh_scanner_api_scanner_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Scanner
         * @description Reload the scanner to refresh its internal state.
         */
        post: operations["reload_scanner_api_scanner_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scanner State
         * @description Get the current state of the scanner.
         */
        get: operations["get_scanner_state_api_scanner_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series List
         * @description Get the list of all series.
         */
        get: operations["get_series_list_api_scanner_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/series/{entity_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series Chapters
         * @description Get chapters for a specific series.
         */
        get: operations["get_series_chapters_api_scanner_series__entity_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/search-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Series
         * @description Search for series by title using MangaDex API.
         */
        get: operations["search_series_api_scanner_search_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/add-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Series
         * @description Add a new series to the scanner.
         */
        post: operations["add_series_api_scanner_add_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/series/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Series
         * @description Delete a series from the scanner.
         */
        delete: operations["delete_series_api_scanner_series__entity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/series/{entity_id}/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Series Downloads
         * @description Reconcile the downloaded chapters for a series.
         */
        put: operations["set_series_downloads_api_scanner_series__entity_id__downloads_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/clean-orphaned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clean Orphaned Files
         * @description Clean orphaned files.
         */
        post: operations["clean_orphaned_files_api_scanner_clean_orphaned_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Logs
         * @description Get the last N lines of the log file.
         */
        get: operations["get_logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Logs
         * @description Clear the log file.
         */
        post: operations["clear_logs_api_logs_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enums/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plugins Enum
         * @description Get the Plugins enum values and list.
         */
        get: operations["get_plugins_enum_api_enums_plugins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enums/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Env Config
         * @description Get the AppEnv configuration values.
         */
        get: operations["get_env_config_api_enums_env_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Spa
         * @description Serve the built React SPA, falling back to index.html for client-side routes.
         */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddSeriesRequest */
        AddSeriesRequest: {
            /** Entity Name */
            entity_name: string;
            /** Entity Id */
            entity_id: string;
            /** Backend */
            backend?: {
                [key: string]: string;
            } | null;
            /**
             * Enable Tracking
             * @default true
             */
            enable_tracking: boolean;
            /**
             * Mark All Tracked
             * @default false
             */
            mark_all_tracked: boolean;
        };
        /** ChapterSummary */
        ChapterSummary: {
            /** Entity Id */
            entity_id: string;
            /** Chapter Number */
            chapter_number: string;
            /** Downloaded */
            downloaded: boolean;
        };
        /** ChaptersResponse */
        ChaptersResponse: {
            /** Chapters */
            chapters: components["schemas"]["ChapterSummary"][];
        };
        /** EnvConfigResponse */
        EnvConfigResponse: {
            /** Version */
            VERSION: string;
            /** Puid */
            PUID: number;
            /** Pgid */
            PGID: number;
            /** Debug Mode */
            DEBUG_MODE: boolean;
            /** Umask */
            UMASK: string;
            /** Config Path */
            CONFIG_PATH: string;
            /** Scan Path */
            SCAN_PATH: string;
            /** Storage Path */
            STORAGE_PATH: string;
            /** Log Path */
            LOG_PATH: string;
            /** Timer Delay */
            TIMER_DELAY: number;
            /** Proxy Url */
            PROXY_URL: string | null;
            /** Delay Per Request */
            DELAY_PER_REQUEST: number;
            /** Log Level */
            LOG_LEVEL: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogsResponse */
        LogsResponse: {
            /** Logs */
            logs: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** PluginsResponse */
        PluginsResponse: {
            /** Default */
            DEFAULT: string;
            /** All */
            all: string[];
        };
        /** ScannerStatusResponse */
        ScannerStatusResponse: {
            /** Busy */
            busy: boolean;
            /** Scanner Initialized */
            scanner_initialized: boolean;
        };
        /** SearchSeriesResponse */
        SearchSeriesResponse: {
            /** Results */
            results: components["schemas"]["SeriesSearchResult"][];
        };
        /** SeriesListResponse */
        SeriesListResponse: {
            /** Series */
            series: components["schemas"]["SeriesSummary"][];
        };
        /** SeriesSearchResult */
        SeriesSearchResult: {
            /** Entity Id */
            entity_id: string;
            /** Title */
            title: string;
            /** Alt Title */
            alt_title: string | null;
            /** All Titles */
            all_titles: string[];
            /** Created At Year */
            created_at_year: number;
            /** Age Rating */
            age_rating: string;
            /** Display Name */
            display_name: string;
        };
        /** SeriesStateItem */
        SeriesStateItem: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
            /** Name Link */
            name_link: string;
            /** Status */
            status: string;
            /** Tracked */
            tracked: boolean;
            /** Latest Chapter */
            latest_chapter: string | null;
            /** Latest Chapter Date */
            latest_chapter_date: string | null;
            /** Metadata Updated */
            metadata_updated: string | null;
            /** Plugin */
            plugin: string;
            /** Plugin Link */
            plugin_link: string;
        };
        /** SeriesStateResponse */
        SeriesStateResponse: {
            /** Series */
            series: components["schemas"]["SeriesStateItem"][];
        };
        /** SeriesSummary */
        SeriesSummary: {
            /** Name */
            name: string;
            /** Entity Id */
            entity_id: string;
        };
        /** SetDownloadsRequest */
        SetDownloadsRequest: {
            /** Downloaded Chapter Ids */
            downloaded_chapter_ids: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_scanner_status_api_scanner_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerStatusResponse"];
                };
            };
        };
    };
    refresh_scanner_api_scanner_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    reload_scanner_api_scanner_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    get_scanner_state_api_scanner_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesStateResponse"];
                };
            };
        };
    };
    get_series_list_api_scanner_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesListResponse"];
                };
            };
        };
    };
    get_series_chapters_api_scanner_series__entity_id__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaptersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_series_api_scanner_search_series_get: {
        parameters: {
            query: {
                title: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_series_api_scanner_add_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSeriesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_series_api_scanner_series__entity_id__delete: {
        parameters: {
            query: {
                entity_name: string;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_series_downloads_api_scanner_series__entity_id__downloads_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDownloadsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clean_orphaned_files_api_scanner_clean_orphaned_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    get_logs_api_logs_get: {
        parameters: {
            query?: {
                max_lines?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_logs_api_logs_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    get_plugins_enum_api_enums_plugins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginsResponse"];
                };
            };
        };
    };
    get_env_config_api_enums_env_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvConfigResponse"];
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
